spring.application.name=MovieBookingSystem
server.port=${PORT:10000}

spring.datasource.url=jdbc:mysql://moviebooking102-divyanshutiwari337-8bff.f.aivencloud.com:14668/defaultdb?useSSL=true&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_p0wZJ7K5PbICFRi6HHV
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=mySuperSecretKeyForJWTThatIsLongEnough123456
jwt.expiration=604800000

tmdb.api.key=9baa3a6e6c6a501e627fdf499d6000dc
